### ISSUE TITLE
[question] [feature request] DDPG VecEnv support

### ISSUE THREAD

**Issue by Enderdead** [hill-a/stable-baselines#679]
I'm currently working to speed up a project using the stable-baselines DDPG algorithm. My environment can be easily converted into VecEnv. But I figured out that your DDPG doesn't support the VecEnv. 
I'm wondering why you didn't implement it? Lack of time, hard to deal with?
Thank you in advance.

**Comment by araffin** [comment]
Hello,

Duplicate of https://github.com/hill-a/stable-baselines/issues/170 (related to #495 )

In short, SAC/TD3/DDPG were designed for using them on real robot, so where multiprocessing is not possible. I would recommend using PPO/A2C for fast training using massive multiprocessing (where sample efficiency is not a problem but wall clock time is)

In theory, SAC/TD3/DDPG could be extended to multiprocessing (this will maybe easier to do so with v3 #576 ), however, in practice, this would complicate the current code (maybe a wrapper around the replay buffer would be a solution).

**Comment by Solliet** [comment]
Perhaps this is solved with #684 ?

**Comment by araffin** [comment]
>Perhaps this is solved with #684 ?

Only partially solved, we would need to change all the logging around (this would complexify the code a bit) and for some algorithm (like DDPG), we are using a `UnvecWrapper` (for legacy reason, not planned in the next version) to have only one environment, so switching to a VecEnv may break other things unfortunately.
