### ISSUE TITLE
[Question] How to save and load a trained model into Tensorflow 1 and 2?

### ISSUE THREAD

**Issue by VSZM** [hill-a/stable-baselines#974]
Hi,

I have a trained model in PPO2 that I can't load and use. Ultimately I would like to be able to load it with Tensorflow 2, but I can't even get it to work with Tensorflow 1. 

I have created a Google Colab notebook that has the full example. https://colab.research.google.com/drive/1ftm9vgiJA8LGwLuUFtaG0aYCS9lUrzET?usp=sharing

Can I get a little help here please?

**Comment by Miffyli** [comment]
Have you taken a look at the issues listed [in the docs](https://stable-baselines.readthedocs.io/en/master/guide/export.html) that also work on exporting the models? Judging by the error it seems to say one of the custom-policy's variables was not initialized properly, but I am not sure if this was before saving or at loading the policy. Personally I would recommend sticking with exporting the variables with `get_parameters` (this will miss the optimizer variables, though) and then re-building the model in the target framework.

**Comment by VSZM** [comment]
> Have you taken a look at the issues listed [in the docs](https://stable-baselines.readthedocs.io/en/master/guide/export.html) that also work on exporting the models? 

Yes, thats how I got to the simple_save and get_parameters hybrid solution. The docs don't give an example on loading these parameters though and since I am kind of new, I missed initializing the parameters after loading them. 

> Personally I would recommend sticking with exporting the variables with get_parameters (this will miss the optimizer variables, though) and then re-building the model in the target framework.

Yep, I tried migrating the network parameters to Pytorch, the model was working, but the predictions were different from the PPO model, to the point that it resulted in poor performance..

> Edit: Try running a `predict` on the policy you created before saving to confirm it works as expected.

Predict works on the PPO2 model as expected, but calling it didn't change tensorflow error. 

**So for future reference here is how to export and import the model to Tensorflow 1:**

```

# Saving model. model here is a stable_baselines model
with model.graph.as_default():
    tf.saved_model.simple_save(model.sess, 'tensorflow_model', inputs={"obs": model.act_model.obs_ph},
                                   outputs={"action": model.act_model._policy_proba})

# Loading model into TF1
global_session = tf.Session()

with global_session.as_default():
    model_loaded = tf.saved_model.load_v2('tensorflow_model')
    model_loaded = model_loaded.signatures['serving_default']

# important step
init = tf.global_variables_initializer()
global_session.run(init)

# Calling the model and converting the result to original format

computation_graph = model2(tf.convert_to_tensor(grid))['action']
with global_session.as_default():
    result = computation_graph.eval()
col = result.argmax()

```

**Comment by Miffyli** [comment]
I take it the problem is solved? You can close the issue if is :) 

> Yep, I tried migrating the network parameters to Pytorch, the model was working, but the predictions were different from the PPO model, to the point that it resulted in poor performance..

Here one must be careful of the layer-differences between TF and PyTorch. Dense/linear and conv layers should be rather straight-forward, but others can be difficult.

**Comment by VSZM** [comment]
Well my end goal would be to load the model to TF2, which I still can't. When I try to load the model in TF2 I get the following error:

```
InvalidArgumentError: Node 'loss/gradients/model/batch_normalization_3/FusedBatchNormV3_1_grad/FusedBatchNormGradV3' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 64. Shapes are [0] and [64].
```
Can be reproduced here: https://colab.research.google.com/drive/18IWxx-eppX2Sjoo2h1hGe0TzCHNiykF1?usp=sharing

It would be very good to have a means to export models from Stable Baselines to a modern API like TF2. But I understand this is not a direct concern of stable baselines.

**Comment by Miffyli** [comment]
Ok, thanks for the info! Indeed this goes outside stable-baselines but it would be a desirable feature for obvious reasons, TF2 replacing TF1 slowly. If you or someone manage to find out how that can be done we'd appreciate a PR to update documentation on that! :)

**Comment by Ugo31** [comment]
> > Have you taken a look at the issues listed [in the docs](https://stable-baselines.readthedocs.io/en/master/guide/export.html) that also work on exporting the models?
> 
> Yes, thats how I got to the simple_save and get_parameters hybrid solution. The docs don't give an example on loading these parameters though and since I am kind of new, I missed initializing the parameters after loading them.
> 
> > Personally I would recommend sticking with exporting the variables with get_parameters (this will miss the optimizer variables, though) and then re-building the model in the target framework.
> 
> Yep, I tried migrating the network parameters to Pytorch, the model was working, but the predictions were different from the PPO model, to the point that it resulted in poor performance..
> 
> > Edit: Try running a `predict` on the policy you created before saving to confirm it works as expected.
> 
> Predict works on the PPO2 model as expected, but calling it didn't change tensorflow error.
> 
> **So for future reference here is how to export and import the model to Tensorflow 1:**
> 
> ```
> 
> # Saving model. model here is a stable_baselines model
> with model.graph.as_default():
>     tf.saved_model.simple_save(model.sess, 'tensorflow_model', inputs={"obs": model.act_model.obs_ph},
>                                    outputs={"action": model.act_model._policy_proba})
> 
> # Loading model into TF1
> global_session = tf.Session()
> 
> with global_session.as_default():
>     model_loaded = tf.saved_model.load_v2('tensorflow_model')
>     model_loaded = model_loaded.signatures['serving_default']
> 
> # important step
> init = tf.global_variables_initializer()
> global_session.run(init)
> 
> # Calling the model and converting the result to original format
> 
> computation_graph = model_loaded(tf.convert_to_tensor(grid))['action']
> with global_session.as_default():
>     result = computation_graph.eval()
> col = result.argmax()
> ```
Hi, could you tell what the grid in  tf.convert_to_tensor(grid))['action']  should be ?

**Comment by VSZM** [comment]
> Hi, could you tell what the grid in tf.convert_to_tensor(grid))['action'] should be ?

@Ugo31 

Yes, that was the input to the model. See the full working example here: https://colab.research.google.com/drive/1ftm9vgiJA8LGwLuUFtaG0aYCS9lUrzET?usp=sharing
